package com.team.noty.event.network;

public final class URLS {
    public static final String domain = "http://api.evfor.fun";
    public static final String imgdomain = "https://evfor.fun";
    public static final String BASE = domain + "/";
    public static final String Category = "categories";
    public static final String CategoryList = "categories/list";
    public static final String Event = "events";
    public static final String Registration = "signup";
    public static final String Login = "user/login";
    public static final String LoginWithSoc = "getauth";
    public static final String RegWithSoc = "setauth";
    public static final String Profile = "profile";
    public static final String Create = "add{x}";
    public static final String Cities = "city/list";
    public static final String EditProfile = "user/editprofile";
    public static final String maineditprofile = "maineditprofile";
    public static final String EventDetails = "events";
    public static final String CommunityDetails = "community";
    public static final String Filter = "filter";
    public static final String EventMessages = "events/{eventId}/messages";
    public static final String PrivateMessages = "events/{eventId}/users/{userId}/messages";
    public static final String EnterEvent = "entertoevent";
    public static final String EnterCommunity = "entertocommunity";
    public static final String ChatBase = domain + "chat/";
    public static final String ChatBaseSocket = "https://evfor.fun";
    public static final String GetNotification = "getnotification";
    public static final String SetNotification = "setnotification";
    public static final String DeleteEvent = "deleteevent";
    public static final String SetFBToken = "setnotytoken";
    public static final String SetUserStatus = "setuserstatus";
    public static final String GetAdminUserList = "getadminuserlist";
    public static final String SetSoc = "setsnid";
    public static final String GetSoc = "getsnid";
    public static final String SetReview = "setreview";
    public static final String GetCountnoty = "getcountnoty";
    public static final String Restore = "resetpassword";
    public static final String GetReview = "getreview";
}
