package evfor.fun.skvader.network;

public final class URLS {
    public static final String domain = "http://api.evfor.fun";
    public static final String imgdomain = "https://evfor.fun";
    public static final String BASE = domain + "/";
    public static final String Category = "categories";
    public static final String CategoryList = "categories/list";
    public static final String Event = "events";
    public static final String Registration = "user/signup";
    public static final String Login = "user/login";
    public static final String LoginWithSoc = "user/getauth";
    public static final String RegWithSoc = "user/setauth";
    public static final String Profile = "user/profile";
    public static final String Create = "add{x}";
    public static final String Cities = "city/list";
    public static final String EditProfile = "user/editprofile";
    public static final String maineditprofile = "user/maineditprofile";
    public static final String EventDetails = "events";
    public static final String CommunityDetails = "community";
    public static final String Filter = "filter";
    public static final String EventMessages = "event/{eventId}";
    public static final String CommunityMessages = "community/{eventId}";
    public static final String PrivateMessages = "user/{userId}";
    public static final String EnterEvent = "events/enter";
    public static final String EnterCommunity = "community/enter";
    public static final String ChatBase = domain + "/chat/";
    public static final String ChatBaseSocket = "https://evfor.fun:3000/";
    public static final String GetNotification = "getnotification";
    public static final String SetNotification = "setnotification";
    public static final String DeleteEvent = "deleteevent";
    public static final String SetFBToken = "user/setnotytoken";
    public static final String SetUserStatus = "setuserstatus";
    public static final String GetAdminUserList = "getadminuserlist";
    public static final String SetSoc = "setsnid";
    public static final String GetSoc = "getsnid";
    public static final String SetReview = "setreview";
    public static final String GetCountnoty = "getcountnoty";
    public static final String Restore = "resetpassword";
    public static final String GetReview = "getreview";
}
